// Pitch prompts from the provided data
export const pitchPrompts = [
  "Overpriced college textbooks",
  "Long commutes",
  "Remote worker isolation",
  "The broken loyalty rewards system",
  "Home energy inefficiency",
  "Plastic packaging waste",
  "Managing screen time for kids",
  "Food waste in restaurants",
  "Inaccessible mental health support",
  "Scheduling doctor appointments",
  "Lost luggage while flying",
  "Buying gifts for coworkers",
  "Staying in touch with aging parents",
  "Poor digital literacy in seniors",
  "Too many streaming platforms",
  "Managing multiple bank accounts",
  "Language barriers when traveling",
  "Personalizing education in schools",
  "Emergency preparedness at home",
  "Job application overload",
  "Subscription fatigue",
  "Managing multiple calendars",
  "Time-consuming meal planning",
  "Buying clothes that fit properly",
  "Maintaining houseplants",
  "Sustainable packaging",
  "Finding local artisans",
  "Last-mile delivery delays",
  "Organizing digital photos",
  "Improving sleep quality",
  "Pet care while traveling",
  "Affordable housing access",
  "Tech recycling",
  "Cyberbullying prevention",
  "Lack of female representation in tech",
  "Networking for introverts",
  "Finding reliable babysitters",
  "Safe online spaces for teens",
  "Supporting new dads",
  "Productivity in noisy environments",
  "Finding parking in cities",
  "Cultural preservation in tourism",
  "Reducing loneliness in cities",
  "Clothing for non-standard sizes",
  "Workplace conflict resolution",
  "Explaining financial products",
  "Decluttering digital devices",
  "Green transportation in suburbs",
  "Simplifying tax filing",
  "Tracking carbon footprint",
  "Reducing meeting fatigue",
  "Supporting family caregivers",
  "Fast access to legal help",
  "Simplifying small claims disputes",
  "Eco-friendly pet products",
  "Reusing construction materials",
  "Matching volunteers to causes",
  "Tools for non-profit fundraising",
  "Inclusive hiring practices",
  "Improving digital privacy",
  "Bridging education gaps",
  "Transparent charity ratings",
  "Access to menstrual care",
  "Financial literacy for teens",
  "Designing inclusive playgrounds",
  "Automating household chores",
  "Tools for citizen journalism",
  "Elderly mobility solutions",
  "Reducing water waste",
  "Secure file sharing",
  "Supporting single parents",
  "Work-travel visa management",
  "Curated cultural events",
  "Managing medical records",
  "Affordable healthy snacks",
  "Supporting long-distance relationships",
  "Eco-tourism tools",
  "Finding ethical brands",
  "Skill certification for freelancers",
  "Simplifying home renovations",
  "Preventing online scams",
  "Virtual mentorship platforms",
  "Improving indoor air quality",
  "Carbon offset transparency",
  "Micro-loans for local businesses",
  "Managing chronic illness",
  "Supporting gig workers",
  "Organ donation awareness",
  "Fast re-skilling tools",
  "Improving resume transparency",
  "Balancing side hustles with work",
  "Emergency translation tools",
  "Reducing food deserts",
  "Local election transparency",
  "Crowdsourced infrastructure fixes",
  "Streamlining school communication",
  "Incentivizing civic engagement",
  "Water access in rural areas",
  "Remote healthcare diagnostics",
  "Neighborhood safety networks",
  "Affordable therapy access",
  "Virtual career fairs"
];

// Venture cards from the provided data
export const ventureCardData = [
  { title: "START-UP", text: "Use this card only when you are broke to gain $2 Billion.", playWindow: "pre" },
  { title: "BOOTSTRAP", text: "Stop a player from receiving $1 Billion.", playWindow: "post" },
  { title: "PIVOT", text: "Swap your pitch card with another player.", playWindow: "pre" },
  { title: "MERGER", text: "Join forces with another player for a joint pitch. Split earnings.", playWindow: "pre" },
  { title: "SERIES A", text: "Gain $1 Billion if you mention a go-to-market strategy.", playWindow: "post" },
  { title: "DOWNROUND", text: "Lose half your current funding.", playWindow: "post" },
  { title: "ANGEL", text: "Earn $500M if your pitch addresses social impact.", playWindow: "post" },
  { title: "VIRAL", text: "Double your funding if most players vote for you.", playWindow: "post" },
  { title: "BLACKOUT", text: "You must pitch without notes or a screen.", playWindow: "mid" },
  { title: "MVP", text: "Deliver your pitch in 30 seconds or less. Succeed to earn $500M.", playWindow: "pre" },
  { title: "EXIT", text: "Cash out half your funding to skip this round.", playWindow: "pre" },
  { title: "ACQUISITION", text: "Steal $500M from the player with the most funding.", playWindow: "post" },
  { title: "TERM SHEET", text: "Negotiate a deal with another player mid-round.", playWindow: "mid" },
  { title: "SPINOFF", text: "Pitch a second idea on the fly for bonus funding.", playWindow: "mid" },
  { title: "DISRUPTION", text: "Pick another player to change their pitch topic.", playWindow: "pre" },
  { title: "IPO", text: "If your pitch is voted #1, gain an extra $1 Billion.", playWindow: "post" },
  { title: "BURN RATE", text: "You lose $250M unless you mention your business model.", playWindow: "post" },
  { title: "MOAT", text: "Explain your competitive advantage. Earn $250M if convincing.", playWindow: "post" },
  { title: "LEAD INVESTOR", text: "Choose one player to automatically vote for you.", playWindow: "post" },
  { title: "TERMS & CONDITIONS", text: "You must include one risk factor in your pitch.", playWindow: "pre" },
  { title: "HYPE", text: "Start your pitch with a tagline. Gain $250M if catchy.", playWindow: "pre" },
  { title: "FOMO", text: "Claim urgency. If 2+ people vote for you, gain $500M.", playWindow: "pre" },
  { title: "NDAs", text: "Your pitch must be vague but intriguing. Earn $500M if voted top 2.", playWindow: "pre" },
  { title: "CASH BURN", text: "Lose $250M for using buzzwords without explanation.", playWindow: "post" },
  { title: "INFLUENCER", text: "Mention social media strategy for a $250M bonus.", playWindow: "post" },
  { title: "SERIES B", text: "Double your earnings if you mention scaling strategy.", playWindow: "post" },
  { title: "DATA ROOM", text: "Include one data point in your pitch to earn $250M.", playWindow: "post" },
  { title: "RUNWAY", text: "If you go over time, lose all funding this round.", playWindow: "pre" },
  { title: "ACCELERATOR", text: "Pitch as if you're in a startup incubator for $500M.", playWindow: "pre" },
  { title: "MENTORSHIP", text: "Pick a player to advise you. You both earn $250M.", playWindow: "pre" },
  { title: "PITCH DECK", text: "Use bullet points only in your pitch for bonus funding.", playWindow: "pre" },
  { title: "TRENDING", text: "Tie your idea to a current event. Gain $500M if relevant.", playWindow: "pre" },
  { title: "VALLEY OF DEATH", text: "You lose all funding unless 2+ people vote for you.", playWindow: "post" },
  { title: "INNOVATOR", text: "Be the only one with a hardware product. Gain $1 Billion.", playWindow: "post" },
  { title: "ETHICS PANEL", text: "Address one ethical issue in your pitch for $250M.", playWindow: "post" },
  { title: "FOUNDER FEUD", text: "Debate another player. Winner gains $500M.", playWindow: "mid" },
  { title: "ROUNDTABLE", text: "All players ask you one question. Answer well to gain $250M.", playWindow: "mid" },
  { title: "HACKATHON", text: "Pitch like it was built in 24 hours. Convince to earn $500M.", playWindow: "pre" },
  { title: "GHOSTWRITER", text: "Another player reads your pitch. Both gain $250M if voted top.", playWindow: "pre" },
  { title: "ADVISORY BOARD", text: "Choose a player to give you bonus feedback. Earn $250M.", playWindow: "pre" },
  { title: "BRANDING", text: "Create a memorable name. Gain $250M if it's voted clever.", playWindow: "pre" },
  { title: "PIVOT FAST", text: "Change your pitch entirely mid-round. Gain $500M if pulled off.", playWindow: "mid" },
  { title: "JOURNALIST", text: "Pitch like you're being interviewed live. Stay composed to earn.", playWindow: "pre" },
  { title: "HARD QUESTIONS", text: "All players may ask a question. Answer confidently for bonus.", playWindow: "mid" },
  { title: "SPEED ROUND", text: "You have half time to pitch. Succeed to earn $500M.", playWindow: "pre" },
  { title: "OVERHEAD", text: "You must list three costs of your idea. Gain $250M if realistic.", playWindow: "post" },
  { title: "TRACTION", text: "Include early customer data. Gain $500M if convincing.", playWindow: "post" },
  { title: "MISSION FIRST", text: "Open with your mission statement. Gain $250M if strong.", playWindow: "pre" },
  { title: "COLD EMAIL", text: "Your pitch must read like a cold email. Win $500M if it works.", playWindow: "pre" }
];

// Helper functions
export function formatFunding(amount: number): string {
  if (amount >= 1000000000) {
    return `$${(amount / 1000000000).toFixed(1)}B`;
  } else if (amount >= 1000000) {
    return `$${(amount / 1000000).toFixed(0)}M`;
  } else {
    return `$${amount.toLocaleString()}`;
  }
}

export function generateAvatar(name: string): string {
  const initials = name.split(' ').map(word => word[0]).join('').toUpperCase();
  return initials.substring(0, 2);
}

export function getAvatarColor(name: string): string {
  const colors = [
    'bg-primary',
    'bg-secondary',
    'bg-purple-500',
    'bg-green-500',
    'bg-amber-500',
    'bg-red-500',
    'bg-blue-500',
    'bg-indigo-500',
    'bg-pink-500',
    'bg-teal-500',
  ];
  
  const index = name.length % colors.length;
  return colors[index];
}
